const GET_USER = "GET_USER";
const GET_DATA = "GET_DATA";
const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
const GET_WISHLIST = "GET_WISHLIST";

export { GET_DATA, GET_USER, ADD_TO_WISHLIST, GET_WISHLIST };
